require 'rubygems'

require_relative 's2c/version'
require_relative 's2c/config'
require_relative 's2c/utils'
require_relative 's2c/logger'
require_relative 's2c/store'
require_relative 's2c/models/unit'
require_relative 's2c/models/planet'
require_relative 's2c/models/ship'
require_relative 's2c/models/fleet'
require_relative 's2c/models/silo'
require_relative 's2c/models/mine'
require_relative 's2c/models/parking'
require_relative 's2c/models/hangar'
require_relative 's2c/jobs/base'
require_relative 's2c/jobs/travel'
require_relative 's2c/jobs/combat'
require_relative 's2c/jobs/upgrade'
require_relative 's2c/jobs/produce_stuff'
require_relative 's2c/jobs/build_ship'
require_relative 's2c/universe'
require_relative 's2c/global'
require_relative 's2c/jsoner'

puts "Loaded S2C gem version #{S2C::VERSION}"