require 'rubygems'

require_relative 's2c/config'
require_relative 's2c/models/planet'
require_relative 's2c/models/construction'
require_relative 's2c/models/mine'
require_relative 's2c/models/ship'
require_relative 's2c/universe'
require_relative 's2c/stats'
require_relative 's2c/utils'