source 'http://rubygems.org'

gemspec

gem "s2c", :path => "/Users/fguillen/Develop/Ruby/SpaceSuckersChronicles/gem"

group :development do
  gem 'rack'
end

group :test do
  gem 'mocha'
  gem 'rack-test'
  gem 'ruby-debug19'
end